### ISSUE TITLE
migration plan

### ISSUE THREAD

**Issue by robjtede** [actix/actix-extras#1]
identity & session currently have dependencies on a release with the time crate changes from -web

TODO:
- [x] create repo readme
- [x] merge crates into workspace (almost)
- [x] set up CI
- [x] ask about an actix-web v3 alpha to hook up session & identity to
- [x] re-point repository metadata items to this repo
- [x] archive redis, protobuf & httpauth repos and update readmes
- [x] delete cors, identity & session crates from -web

MIGRATION:
- [x] actix-cors
- [x] actix-identity
- [x] actix-redis
- [x] actix-protobuf
- [x] actix-web-httpauth
- [x] actix-session

**Comment by robjtede** [comment]
thoughts on the setup of this repo and the plan ideas @JohnTitor ?

**Comment by JohnTitor** [comment]
Sounds good, I'll set up CI for this repo soonish.

**Comment by dunnock** [comment]
FWIW actix-identiti and actix-session do not compile as latest actix-http and actix-web published to crates.io use time 0.1.42

**Comment by JohnTitor** [comment]
It doesn't matter here since the current code isn't published and no one relies on this repository. Actually, we don't include them in the workspace now. Once the new alpha version is released, we should update dependencies and release their new versions.

**Comment by JohnTitor** [comment]
actix-protobuf: migration and archive work are done.

**Comment by JohnTitor** [comment]
Okay, migration is almost done. The remaining thing is deleting {cors, identity, session} from actix-web repo but I'm cautious because some users may depend on them by pointing to that repo. But indeed we should delete them at some point.

**Comment by mocsy** [comment]
Any user depending directly to the git repo needs to update their link to the new repo.
They'll notice when their builds fail, it's not like we have to semver our git as well.
Just make sure the README.md in the old repo mentions at the headline where these were moved, so they can find out what's the problem fast.
