### ISSUE TITLE
Session: time to live

### ISSUE THREAD

**Issue by torepettersen** [actix/actix-extras#100]
Extend `Session` api to getting time until a key in the session will expire. Similar to Redis command `ttl`.

Extend `Session` api to reset ttl back to the initial time. For sessions with Redis, the `expire` command could be used.

**Comment by gabucito** [comment]
Hello, I am having the same issue.
So far I am thinking of using the RedisActor and sending the commands manually to reset the ttl on Redis.

Were you able to find a better solution?

**Comment by robjtede** [comment]
the 0.7.0 release supports TTL on sessions
