### ISSUE TITLE
Allow Access-Control-Allow-Origin in Actix-CORS

### ISSUE THREAD

**Issue by NielDuysters** [actix/actix-extras#103]
I have Rust code running on api.myexample.com. Now I want that codes from other domains can make GET/POST request to api.myexample.com.

Now this gives the following error:
```

[Error] Origin http://othersitecallingtheapi.com is not allowed by Access-Control-Allow-Origin

```

I should be able to fix this somehow by configuring the CORS. But I don't see anywhere in the Actix-CORS documentation on how to allow `Access-Control-Allow-Origin`.

Thanks!

**Comment by robjtede** [comment]
https://docs.rs/actix-cors/0.3.0/actix_cors/struct.Cors.html#method.allowed_origin
