### ISSUE TITLE
How to use it with websockets?

### ISSUE THREAD

**Issue by Boscop** [actix/actix-extras#12]
I want to do HTTP Basic auth when a websocket connection request arrives, how can I do it with this crate? (And then I want to set the auth cookie with [`CookieIdentityPolicy`](https://actix.rs/actix-web/actix_web/middleware/identity/index.html)..)

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers

> The server can send other headers like Set-Cookie, or ask for authentication or redirects via other status codes, before sending the reply handshake.

**Comment by robjtede** [comment]
From the server's perspective, authentication on the request is no different in WS than in HTTP.

The trouble is that browsers do not support anything other than cookie auth, to my knowledge and ignoring insecure workarounds. Basic auth requires a header, and you cannot tell JavaScript to send one, so you cannot do it.

**Comment by Boscop** [comment]
@robjtede Thanks for the reply :)

So when initiating a WS connection from a Rust/Wasm frontend, it's also not possible to set an auth header?

Assuming the user is already logged in (not via WS) with a session cookie, will that cookie be sent along with the WS connection initiation request, so that the server can check if the connecting user is authenticated?

If so, wouldn't that be the easiest way to handle WS authentication if there is already a normal user login mechanism?

Or are there any downsides to this? 
(The server could also disconnect the WS connection at the same time when the cookie session expires, if it's still active then.)

**Comment by robjtede** [comment]
> will that cookie be sent along with the WS connection initiation request

Tes, this is the easiest way to do auth, and as such...

> everything should be handled by sending and receiving messages through the WebSocket including auth.

I slightly retract this statement.
