### ISSUE TITLE
Proposal: move `RedisSession` to `actix-session`

### ISSUE THREAD

**Issue by arniu** [actix/actix-extras#131]

**Comment by robjtede** [comment]
please expand on the reasoning

**Comment by arniu** [comment]
`actix-redis` is a general-purpose library.
For the people a) who use redis as a session store, they have to install `actix-redis` and `actix-session` with default features disabled; b) the others, they have to disable the default features of `actix-redis`. Both of them need more work.

If we move `RedisSession` to `actix-session` and remove `cookie-session` from the default features (see #132), both of them will do less works.

**Comment by robjtede** [comment]
Expecting the dependents of actix-session to also download a redis library even if they're only using cookie session or providing some other session backend seems like a stretch.

**Comment by robjtede** [comment]
Oh, no default features on actix-session. I see what you're suggesting.

**Comment by robjtede** [comment]
As seen in https://github.com/actix/examples/blob/master/redis-session/Cargo.toml there is no need to change features for either crate in order to use them. I'd prefer to keep the redis functionality with the redis library.

**Comment by arniu** [comment]
I mean, if someone use this just to access redis but NOT want to use cookie sessions, they have to disable default features, or they'll add unused packages.
