### ISSUE TITLE
Proposal: remove `cookie-session` from default features of `actix-session`

### ISSUE THREAD

**Issue by arniu** [actix/actix-extras#132]

**Comment by robjtede** [comment]
please expand on the reasoning

**Comment by arniu** [comment]
If `RedisSession` moved here, we'll have two session stores included. Then people pick one at their choice, without to disable default features.

And more, if someone want to use or implement other session stores, they do have to configure `actix-session`.

**Comment by robjtede** [comment]
I'm an advocate for sensible defaults and I don't think removing this from default features is significantly advantageous even when not using cookie sessions.
