### ISSUE TITLE
[httpauth] Optional credentials

### ISSUE THREAD

**Issue by sanpii** [actix/actix-extras#137]
## Expected Behavior
Set `Authorization` header optional.

## Current Behavior
If I don’t send the `Authorization` header, the extractor fail and returns a 401 error.

## Possible Solution
Impl `AuthExtrator` for `Option<BasicAuth>` and `Option<BearerAuth>`.

## Context
Some routes aren’t require authentication, typically route for registration/sign in.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.48.0 (7eac88abb 2020-11-16)
* actix-web-httpauth crate Version: 0.5.0

**Comment by GopherJ** [comment]
@sanpii I'm always using this PR: https://github.com/actix/actix-extras/pull/6

ping @Dowwie to give a solution

**Comment by robjtede** [comment]
Optional extractors are done using `Option<T>` in the handler parameters where you'd put your extractor (T) usually.

In your case that not all routes require auth, then consider only applying the middleare to those that do need it using `Scope::wrap` or `Resource::wrap` instead of `App::wrap`.
