### ISSUE TITLE
Unsucsesful Authentication returns 500, not 401/403

### ISSUE THREAD

**Issue by venil7** [actix/actix-extras#140]
## Expected Behavior
 response should return 401/403 resonse

## Current Behavior
500 is being thrown

## Steps to Reproduce (for bugs)
```Rust
// from example
async fn validator(
    req: ServiceRequest,
    _credentials: BasicAuth,
) -> Result<ServiceRequest, Error> {
    Err(Error::from("bad credentials"))
}
```

## Context
Isnt the whole point of authentocation middleware to return 401/403 on failed authentication?
Instead it seem to propagate error, and result in 500 

## Your Environment
* Rust Version rustc 1.48.0 (7eac88abb 2020-11-16)
* Actix-* actix-web = "3"

**Comment by Overdash** [comment]
_(Anyone feel free to correct me if I'm wrong)_ 
Actix-web automatically throws Error 500 for unhandled errors as described [here](https://actix.rs/docs/errors/):
![image](https://user-images.githubusercontent.com/21345231/113208495-c50b3700-9269-11eb-9293-5b39364990a9.png).

I think what you could do here is use `actix_web::error::ErrorUnauthorized` instead, which returns a 401 error code.

**Comment by robjtede** [comment]
`Error::from(String)` will create a 500 error and is used solely for example. (Though it could be improved.) Use any of the helper functions (or create your own error) from this mod: https://docs.rs/actix-web/3.3.2/actix_web/error/index.html.
