### ISSUE TITLE
actix-session incompatible with the new v4 beta

### ISSUE THREAD

**Issue by MikeGlennFWC** [actix/actix-extras#146]
using actix-session like this
```rust
.wrap(
    CookieSession::signed(&decode(env::var("APP_KEY").unwrap()).unwrap())
        .domain(env::var("APP_URL").unwrap())
        .name("queue_rs")
        .path("/")
        .secure(false),
)
```

results in 

```rust
error[E0277]: the trait bound `CookieSession: Transform<actix_web::app_service::AppRouting, ServiceRequest>` is not satisfied
   --> src/main.rs:268:17
    |
268 | /                 CookieSession::signed(&decode(env::var("APP_KEY").unwrap()).unwrap())
269 | |                     .domain(env::var("APP_URL").unwrap())
270 | |                     .name("queue_rs")
271 | |                     .path("/")
272 | |                     .secure(false),
    | |__________________________________^ the trait `Transform<actix_web::app_service::AppRouting, ServiceRequest>` is not implemented for `CookieSession`
```

deps:
actix-web = "4.0.0-beta.1"
actix-rt = "2.0.0-beta.1"
actix-files = "0.6.0-beta.1"
actix-session = "0.4.0"

Also great job on the tokio upgrade, i see you guys have been working hard to get that upgraded.

**Comment by robjtede** [comment]
It'll be too much churn to keep this repo up to date with the frequent breaking changes during this beta period.

There's a PR open for the upgrade you can use as a git dependency it you wish.

**Comment by MikeGlennFWC** [comment]
Thanks Rob,

for anyone else, here is the branch of the PR.

https://github.com/andy128k/actix-extras/tree/update-dependencies

**Comment by NikosEfthias** [comment]
@MikeGlennFWC the link seems to be broken

**Comment by TheGlenn88** [comment]
@NikosEfthias my link to the branch is irrelevant now due to the PR being merged.

Please check https://github.com/actix/actix-extras/pull/144

**Comment by NikosEfthias** [comment]
I am using latest version of actix-cors yet I get error message indicating the incompatibility

**Comment by NikosEfthias** [comment]
![image](https://user-images.githubusercontent.com/9097437/112737835-8e35d800-8f6e-11eb-947f-c311a530fb0f.png)

**Comment by NikosEfthias** [comment]
I dont know what I am missing but actix-cors most deffinetely is not actix-4 compatible at this point

**Comment by TheGlenn88** [comment]
It appears that is the case. actix-web 4 is still in beta so this should be expected still.

My original issue was with actix-session. Yours appears to be actix-cors. You should raise a new issue so the maintainers can track it there.

**Comment by NikosEfthias** [comment]
@TheGlenn88 btw do you know how does one use a workspace from a git repo say actix-cors from actix-extras repo.
The cargo book doesnt seem to have any documentation explaining how to do this?

**Comment by TheGlenn88** [comment]
It's is in the cargo book. It's under the patch section.

https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html?highlight=Patch#the-patch-section

I'm sorry i can't give you a more direct example right now. If you check out that section it should hopefully give you the direction you need.

**Comment by TheGlenn88** [comment]
Also, from memory, for how actix-extras is set up. It may help to clone the repo and use the directory on your local disk to actix-cors instead of pointing directly to a great repo.

**Comment by NikosEfthias** [comment]
thanks it is a great help and as you suggest it seems to be an easier way to do just to clone that is
