### ISSUE TITLE
actix-redis how to change redis db and use password to auth

### ISSUE THREAD

**Issue by wzhsh90** [actix/actix-extras#151]
RedisSession::new("127.0.0.1:6379")

How can i link to redis?

**Comment by clintonwoo** [comment]
There's a pull request open which extends the accepted URLs to add password capability in `actix-redis`.
https://github.com/actix/actix-extras/pull/167

The pkg isn't really usable without supporting Redis passwords.

**Comment by fakeshadow** [comment]
In redis authentication is just a regular command. actix-redis can do authentication and the only thing you need to do is send "AUTH" command through it. https://redis.io/commands/auth

The current setup is not noob friendly for beginner indeed and that's what the PR is able. It does not mean the current release can not do authentication at all.

**Comment by clintonwoo** [comment]
Oh, there you go, yep you are right and thanks for the response.

So to access the Redis actor and `AUTH` would the app need to access it through an Actix request handler extractor? So maybe we'd need to make a new middleware if we wanted to `AUTH` for every Redis connection?

One more question, seems like this library will create a new session for every request to the server? If we wanted to only create new sessions when a user logs in or registers is there any capability to get that behavior?
