### ISSUE TITLE
actix-redis: Panicked at 'System is not running' in tests when using the latest actix-web and actix-rt crates 

### ISSUE THREAD

**Issue by imDema** [actix/actix-extras#154]
## Expected Behavior

`RedisSession::new` should not panic when testing under `actix_rt::test`

## Current Behavior

`RedisSession::new` panics when testing under `actix_rt::test`
```
running 1 test
thread 'test' panicked at 'System is not running', /home/dema/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/lib.rs:31:9
```

## Steps to Reproduce (for bugs)

Dependencies in Cargo.toml:
```toml
[dependencies]
actix-web = "3.3"
actix-redis = "0.9"

[dev-dependencies]
actix-rt = "2.0"
```
main.rs
```rust
use actix_redis::RedisSession;

#[actix_web::main]
async fn main() {
    let s = RedisSession::new("127.0.0.1:6379", &[0;32]);
}

#[cfg(test)]
#[actix_rt::test]
async fn test() {
    let s = RedisSession::new("127.0.0.1:6379", &[0;32]);
}
```

1. `cargo run` (works)
2. `cargo test` (panics)

## Context

I tried using the latest actix_rt release for testing using the latest actix-redis release alongside the latest actix_web release

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.49.0 (e1884a8e3 2020-12-29)
* Actix-* crate(s) Version:
  * actix-web v3.3.2
  * actix-session v0.4.0
  * actix-redis v0.9.1

**Comment by fakeshadow** [comment]
actix-rt v2 does not supprot actix-web v3.

**Comment by imDema** [comment]
I got into this situation since I tried upgrading sqlx to 0.5 which uses actix-rt 2 so I upgraded actix_rt thinking it would work.
So basically I should stick to sqlx 0.4 and actix-rt 1.1 until actix-web supports actix-rt 2?

**Comment by fakeshadow** [comment]
actix-rt release v2 early mainly to unblock crates from adopting tokio 1.0. 
actix-web v4 is still a work in progress and may take some time to release. So yes you probably want to stick with actix-web v3 and sqlx for a little bit longer.

**Comment by imDema** [comment]
Ok, thanks

**Comment by robjtede** [comment]
https://github.com/actix/actix-web/issues/1944
