### ISSUE TITLE
actix-redis incompatible with redis-async >= "0.7"

### ISSUE THREAD

**Issue by Flash1232** [actix/actix-extras#155]
It seems the `actix-redis 0.9.1` `Command` struct does not play well with newer redis-async crates. In particular on `redis-async 0.8.1`:
```shell
error[E0308]: mismatched types
  --> src/authenticator/authenticate.rs:17:35
   |
17 |     let blub = r_dba.send(Command(resp_array!["HGET", "asdasd", "token"]));
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `actix_redis::RespValue`, found enum `redis_async::resp::RespValue`
   |
   = note: perhaps two different versions of crate `redis_async` are being used?
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by fakeshadow** [comment]
https://github.com/actix/actix-extras/blob/81c48930c4c89a2856bfc37ba6feb02040a93d36/actix-redis/Cargo.toml#L42

actix-redis uses 0.6x. Try to downgrade and pin your redis-async version. 
PR for bumping the version for acitx-redis is also welcomed.
