### ISSUE TITLE
actix-session's purge() function does not apply (nor does remove()) when done in an HTTP Post request

### ISSUE THREAD

**Issue by john01dav** [actix/actix-extras#157]
This issue was originally reported on the main actix issue tracker [here](https://github.com/actix/actix-web/issues/2007) due to [this](https://github.com/actix/actix-extras/issues/136) issue. I'd like to report it here as well so hopefully the right person finds it. 

Also, are these projects still maintained? If not, I may be interested in taking over at least actix-session.

**Comment by JohnTitor** [comment]
Duplicate of #158
