### ISSUE TITLE
 the trait `actix::Actor` is not implemented for `RedisActor`

### ISSUE THREAD

**Issue by yutiansut** [actix/actix-extras#169]
error start in actix-redis 0.9.2 with actix ==0.11

```
error[E0277]: the trait bound `RedisActor: actix::Actor` is not satisfied
  --> src\db\redis.rs:21:23
   |
21 | pub fn set_bar(redis: Addr<RedisActor>, key: &str, data: String) {
   |                       ^^^^^^^^^^^^^^^^ the trait `actix::Actor` is not implemented for `RedisActor`
   | 
  ::: C:\Users\yutia\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-0.11.0\src\address\mod.rs:77:20
   |
77 | pub struct Addr<A: Actor> {
   |                    ----- required by this bound in `actix::Addr`
```

**Comment by JohnTitor** [comment]
Note that actix-redis 0.9 is incompatible with actix 0.11. Use actix 0.10 for now.

**Comment by yutiansut** [comment]
but the cargo.toml is 0.11
https://github.com/actix/actix-extras/blob/master/actix-redis/Cargo.toml#L34

**Comment by JohnTitor** [comment]
It's not published yet, you should check https://github.com/actix/actix-extras/tree/redis-v0.9.2/actix-redis for 0.9.2.

**Comment by yutiansut** [comment]
> It's not published yet, you should check https://github.com/actix/actix-extras/tree/redis-v0.9.2/actix-redis for 0.9.2.

all right anyway thanks~
