### ISSUE TITLE
actix-cors is not compatible with actix-4

### ISSUE THREAD

**Issue by NikosEfthias** [actix/actix-extras#171]
![image](https://user-images.githubusercontent.com/9097437/112738400-c2f85e00-8f73-11eb-8609-5cff716d8410.png)

* Rust Version (I.e, output of `rustc -V`): `rustc 1.51.0 (2fd73fabe 2021-03-23)`
* Actix-* crate(s) Version: `4-beta.4`

**Comment by robjtede** [comment]
beta will be available soon

**Comment by NikosEfthias** [comment]
@robjtede  cool, thanks.
How soon do you think it will be ?

**Comment by sysmat** [comment]
- actix-web = "4.1.0"
- actix-cors = "0.6.3"
- still not not compatible, error: `the trait `Clone` is not implemented for `Cors``

any progress?

**Comment by robjtede** [comment]
You need to create the Cors middleware inside the HttpServer::new closure to avoid the need to clone.
