### ISSUE TITLE
HttpAuthentication Middleware trait bound issues with Transform<ScopeService, _>

### ISSUE THREAD

**Issue by Overdash** [actix/actix-extras#172]
## Expected Behavior
Able to use `actix_web_httpauth::middleware::HttpAuthentication;`  

## Current Behavior
Type mismatches and trait bound issues:

Type mismatch:
```rust
error[E0631]: type mismatch in function arguments
  --> src\main.rs:90:58
   |
90 |         let auth_middleware = HttpAuthentication::bearer(jwt::validator);
   |                                                          ^^^^^^^^^^^^^^
   |                                                          |
   |                                                          expected signature of `fn(actix_web::service::ServiceRequest, BearerAuth) -> _`
   |                                                          found signature of `fn(ServiceRequest, BearerAuth) -> _`
   |
   = note: required by `HttpAuthentication::<BearerAuth, F>::bearer`
```

Trait Bound issue:
```rust
error[E0277]: the trait bound `HttpAuthentication<BearerAuth, fn(ServiceRequest, BearerAuth) -> impl std::future::Future {validator}>: Transform<actix_web::scope::ScopeService, ServiceRequest>` is not satisfied
   --> src\main.rs:105:27
    |
105 |                     .wrap(auth_middleware)
    |                           ^^^^^^^^^^^^^^^ the trait `Transform<actix_web::scope::ScopeService, ServiceRequest>` is not implemented for `HttpAuthentication<BearerAuth, fn(ServiceRequest, BearerAuth) -> impl std::future::Future {validator}>`


```

## Possible Solution
Could be a mismatch of actix-web dependencies? I don't see a `actix_web::service::ServiceRequest` existing in any of my dependencies.

## Steps to Reproduce (for bugs)
The code does not compile - produced a minimal example:
```rust
// in jwt.rs

pub async fn validator(req: actix_web::dev::ServiceRequest, cred: BearerAuth) -> std::result::Result<ServiceRequest, ActixError> {
    let configs = extract_config::<JWTConfigs>().unwrap();
    match verify(cred.token(), &configs.jwt_secret).await {
        Ok(_token) => {
            Ok(req)
        }
        Err(e) => {
            trace!("User failed JWT Validation: {}", e);
            Err(ErrorUnauthorized("invalid token"))
        }
    }
}

// somewhere in main.rs
        let auth_middleware = HttpAuthentication::bearer(jwt::validator);
        App::new()
            .wrap(middleware::Logger::default())
            // have also tried moving the auth_middleware wrap here <--
            .data(context)
            .route("/", web::get().to(index))
            .configure(AuthEndpoint::routes)
            .service(
                // NOTE: These endpoints are JWT-Auth protected
                web::scope("v1")
                    .wrap(auth_middleware)
                    .configure(....)
                    .....
            )

```

## Context
Unable to compile - setup is similar to example found [here](https://github.com/actix/actix-extras/blob/master/actix-web-httpauth/examples/middleware.rs)

## Your Environment

* Rust Version (I.e, output of `rustc -V`): 1.51
* Actix-* crate(s) Version:
Actix-web: **4.0.0-beta.4**
Actix-web-httpauth: **0.5**

**Comment by vbrandl** [comment]
Same problem with `actix-cors` but I guess the `acitx-extra` libs just have not been implemented against the upcoming major release

**Comment by Overdash** [comment]
> Same problem with `actix-cors` ~but I guess the `acitx-extra` libs just have not been implemented against the upcoming major release~
> 
> The versions that are implemented against the upcoming major version are not yet published to crates.io
> But the changes are already in the master branch: https://github.com/actix/actix-extras/blob/master/actix-web-httpauth/Cargo.toml
> 
> For now, you can specify your dependency like this:
> 
> ```
> actix-web-httpauth = { git = "https://github.com/actix/actix-extras", branch = "master" }
> ```

Can confirm this is circumvention is working for now (had to also explicitly import `actix-service = "2.0.0-beta.5"`.
I guess once `actix v4` is released this will be an non-issue.

**Comment by Overdash** [comment]
Found out the reason it wasn't working -> If httpauth does not find the header, it auto rejects the request without even hitting the middleware. So you must include the Auth Bearer header in your request for the custom middleware to be processed. Closing this issue :)
