### ISSUE TITLE
the trait bound `serde_json::Error: ResponseError` is not satisfied

### ISSUE THREAD

**Issue by shanliu** [actix/actix-extras#183]
```
error[E0277]: the trait bound `serde_json::Error: ResponseError` is not satisfied
   --> C:\Users\PC\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-session-0.5.0-beta.1\src/lib.rs:151:44
    |
151 |             Ok(Some(serde_json::from_str(s)?))
    |                                            ^ the trait `ResponseError` is not implemented for `serde_json::Error`
    |
    = note: required because of the requirements on the impl of `From<serde_json::Error>` for `actix_web::Error`
    = note: required by `std::convert::From::from`
```
## Your Environment
OS Name:                   Microsoft Windows 10
OS Version:                10.0.19042 N/A Build 19042

* Rust Version (I.e, output of `rustc -V`):
rustc 1.53.0-nightly (7f4afdf02 2021-04-22)
actix-web = "~4.0.0-beta.6"
actix-session = "0.5.0-beta.1"

**Comment by miraclx** [comment]
Since `actix-http 4.0.0-beta.6` (https://github.com/actix/actix-web/pull/2148), `ResponseError` is no longer impl for `serde_json::Error`

You can go ahead to map and wrap that `Error`:

```diff
- Ok(Some(serde_json::from_str(s)?))
+ Ok(Some(serde_json::from_str(s).map_err(actix_web::error::JsonPayloadError::Serialize)?))
```

**Comment by shanliu** [comment]
> Since `actix-http 4.0.0-beta.6` ([actix/actix-web#2148](https://github.com/actix/actix-web/pull/2148)), `ResponseError` is no longer impl for `serde_json::Error`
> 
> You can go ahead to map and wrap that `Error`:
> 
> ```diff
> + use actix_web::error::JsonPayloadError;
> +
> - Ok(Some(serde_json::from_str(s)?))
> + Ok(Some(serde_json::from_str(s).map_err(JsonPayloadError::Deserialize)?))
> ```
> 
> Also see: Cargo.toml's [[patch]](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) section

actix-session crate error..

**Comment by miraclx** [comment]
Mind including the error?

**Comment by shanliu** [comment]
can't use actix-session = "0.5.0-beta.1"
bad crate.

**Comment by JohnTitor** [comment]
Please refrain from using offensive words.
Note that it's a beta version and syncing the actix-* crates are hard to maintain (in particular, it's on the actix-extras repo).

**Comment by nalpr** [comment]
you should stick to 
actix-service = "=2.0.0-beta.5"
actix-web = "=4.0.0-beta.5"
a bit longer and wait for new versions.
