### ISSUE TITLE
Cors headers not set with Actix_Cors using Actix_Web server

### ISSUE THREAD

**Issue by PSPanesar** [actix/actix-extras#184]
I have written a web server in Rust using Actix_Web. Im preparing it for production so I wanted to add Cors to the server to improve security. I have used the Actix_Cors package to do that and implemented a test with a basic server. When calling the end point however the Cors headers are not set and the server accepts connections from any client even though I have restricted it to a domain that should not work. I'm not sure why this isn't working and have debugged it the best I can. I have followed the instructions for setting up my server precisely as in the Actix-Cors documentation. Could someone help me work out why its not working?

## Expected Behavior
Cors should block domains that are not listed as allowed

## Current Behavior
Cors allows all domains for requests and GET request succeeds 

## Steps to Reproduce (for bugs)
main function
```rust
use actix_cors::Cors;
use actix_web::{get, http, web, App, HttpRequest, HttpResponse, HttpServer};

#[get("/index.html")]
async fn index(req: HttpRequest) -> &'static str {
    "<p>Hello World!</p>"
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        let cors = Cors::default()
            .allowed_origin("https://www.rust-lang.org/")
            .allowed_origin_fn(|origin, _req_head| origin.as_bytes().ends_with(b".rust-lang.org"))
            .allowed_methods(vec!["GET", "POST"])
            .allowed_headers(vec![http::header::AUTHORIZATION, http::header::ACCEPT])
            .allowed_header(http::header::CONTENT_TYPE)
            .max_age(3600);

        App::new().wrap(cors).service(index)
    })
    .bind(("127.0.0.1", 8080))?
    .run()
    .await;

    Ok(())
}
```
My Cargo.toml

```toml
[dependencies]
actix-cors = "0.5.4"
actix-web = "3.3.2"
```

The successful result of a GET call from localhost - 

```bash
GET /index.html HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/2.4.0



HTTP/1.1 200 OK
content-length: 19
content-type: text/plain; charset=utf-8
date: Tue, 04 May 2021 07:47:02 GMT

<p>Hello World!</p>
```

## Your Environment
actix-cors = "0.5.4"
actix-web = "3.3.2"
rustc version = 1.50.0

**Comment by robjtede** [comment]
CORS is activated when the Origin header is sent. Browsers do this automatically but using HTTPie you would need to send it manually.

```
http :8080/index.html Origin:example.com
````

**Comment by PSPanesar** [comment]
Hi,
I tried this using my web browser as well and the same issue happens. Cors is not applied. See screen grab.

<img width="1110" alt="Screenshot 2021-05-04 at 11 11 05" src="https://user-images.githubusercontent.com/10487983/116989346-88e44f80-acc9-11eb-8dfd-4137b22bd4d0.png">

**Comment by robjtede** [comment]
That is expected. It's not a cross origin request; note that the Origin header is not sent.

I'd recommend reading the MDN pages on CORS to get an idea of why it exists and when it is used in browsers.

**Comment by PSPanesar** [comment]
Thanks. I'll have a look deeper into it. Appreciate the advice.
