### ISSUE TITLE
actix_cors doesn't send CORS headers other middleware errors

### ISSUE THREAD

**Issue by s97712** [actix/actix-extras#19]
## Expected Behavior
Keep setting cors response headers, even if other middleware has errors.

## Current Behavior
If an error occurs in the middleware chain, actix_cors will return this error directly, and doesn't setting any response headers.

## Your Environment
* Rust Version (I.e, output of `rustc -V`):
* Actix Web Version: 2.0.0
* Actix Cors Version: 0.2.0

**Comment by s97712** [comment]
> @s97712 can you add the rust version and actix-web/actix-cors version to the issue please.

Has added

**Comment by GopherJ** [comment]
Same error.

**Comment by wketting** [comment]
Same error

**Comment by luowei-D** [comment]
Same error

**Comment by robjtede** [comment]
A middlware error is indicative of a fatal failure. All middlwares should return `Ok(...)` responses if the error is recoverable. This is a different expectation to handlers.

**Comment by tsingroo** [comment]
i want to know how to fix it
