### ISSUE TITLE
Conflict in CORS and Compress middlewares

### ISSUE THREAD

**Issue by omid** [actix/actix-extras#191]
When I use CORS and Compress middlewares, order of wrapping is important.

## Expected Behavior
Web application server runs!

## Current Behavior
I see a warning like: `expected enum ResponseBody, found enum AnyBody`

## Steps to Reproduce (for bugs)
1. In this example, https://github.com/actix/actix-extras/blob/master/actix-cors/examples/cors.rs
2. First enable actix-web's default-features (which is disabled in the repo)
3. Then add `.wrap(middleware::Compress::default())` _after_ the CORS wrap, and test the example (cargo run --example cors), it works.
4. Then revert step 3 and add `.wrap(middleware::Compress::default())` _before_ the CORS wrap, and run the example, it doesn't work.

## Your Environment
Rust 1.53
actix-cors 0.6.0-beta.2
actix-web 4.0.0-beta.8

**Comment by kunjee17** [comment]
Having the same issue. And your work around of moving things around did work for me.

**Comment by Luca-spopo** [comment]
Same issue here, the workaround works but I am unsure what impact it has (I guess in the other order, only CORS requests would not get compressed?)

**Comment by pashinin** [comment]
Not only compress middleware. I had to switch this:

```
.wrap(middleware::Logger::default())
.wrap(Cors::permissive())
```

```
77 |             .wrap(Cors::permissive())
   |              ^^^^ expected struct `middleware::logger::StreamLog`, found enum `AnyBody`
   |
   = note: expected struct `ServiceResponse<middleware::logger::StreamLog<AnyBody>>`
              found struct `ServiceResponse<AnyBody>`
```

to this:

```
.wrap(Cors::permissive())
.wrap(middleware::Logger::default())
```

no error
