### ISSUE TITLE
Help - use custom data in actix_web_httpauth::extractors::basic::{BasicAuth, Config};

### ISSUE THREAD

**Issue by bjin01** [actix/actix-extras#196]
This is not bug but I would appreciate any feedback and hint how to achieve this. 
I would like to use my custom struct object data in a validator function that by default only get BasicAuth and ServiceRequest. 

In below fn I would also pass my struct object that hold's the pre-set username and password that I will use to match against incoming http basic auth data.

```
async fn validator(req: ServiceRequest, credentials: BasicAuth) -> Result<ServiceRequest, Error> {
    
    let config = req
        .app_data::<Config>()
        .map(|data| data.clone())
        .unwrap_or_else(Default::default);
    println!("{:?}", config);
    if credentials.user_id().eq("suma") && credentials.password().unwrap().eq("restapi") {
        Ok(req)
    } else {
        Err(AuthenticationError::from(config).into())
    } 
    
}
```
Desired solution:
```
async fn validator(req: ServiceRequest, credentials: BasicAuth, m: &MyData) -> Result<ServiceRequest, Error> {
    
    let config = req
        .app_data::<Config>()
        .map(|data| data.clone())
        .unwrap_or_else(Default::default);
    println!("{:?}", config);
    if credentials.user_id().eq(m.username) && credentials.password().unwrap().eq(m.password) {
        Ok(req)
    } else {
        Err(AuthenticationError::from(config).into())
    } 
    
}
```

**Comment by robjtede** [comment]
place the credentials in app_data and extract them in the validator fn from service request

**Comment by bjin01** [comment]
> place the credentials in a struct in app_data and extract them in the validator fn from service request

Thanks for your reply. This app_data does not work for my code as the fn validator is created as below:

```async fn main() -> std::io::Result<()> {
    
    let yaml_file = matches.value_of("test.yaml");
    let mut suma_info: SumaInfo = SumaInfo::new(&String::from(yaml_file));
    suma_info.hostname.insert_str(0, "http://");
    suma_info.hostname.push_str("/rpc/api");

    ...



    HttpServer::new(move || {
        let auth = HttpAuthentication::basic(validator);
        OtherApp::new()
            .data(suma_info.clone())
            .wrap(middleware::Logger::new("%a %{User-Agent}i"))
            .wrap(auth)
            .service(getinfo)
            .route("/patch", web::get().to(patch))
            .route("/suma", web::get().to(|| suma("ok".to_string())))
    })
    .bind_openssl("0.0.0.0:".to_owned() + &server_port.to_string(), builder)?
    .run()
    .await
}
```
Any other idea?

**Comment by wuriyanto48** [comment]
here is my working code for this,
`sync fn basic_auth_validator(req: ServiceRequest, 
    credentials: BasicAuth) -> ActixResult<ServiceRequest, ActixError> {
    if req.app_data::<web::Data<super::AppParam>>().is_none() {
        return Err(ErrorUnauthorized(CustomError::Unauthorized));
    }

    if credentials.password().is_none() {
        return Err(ErrorUnauthorized(CustomError::Unauthorized));
    }

    let app_param = req.app_data::<web::Data<super::AppParam>>().unwrap();
    if app_param.config.basic_auth_username.ne(&credentials.user_id().to_string()) ||
        app_param.config.basic_auth_password.ne(&credentials.password().unwrap().to_string()) {
        
        logger::error!("credentials invalid : {:#?}", credentials.user_id());
        return Err(ErrorUnauthorized(CustomError::Unauthorized));
    }

    Ok(req)
}`
