### ISSUE TITLE
actix-redis purge() might be OK to execute optimistically.

### ISSUE THREAD

**Issue by kogai** [actix/actix-extras#199]
Thanks for developing a great library!

I'm not sure if this suggestion would be reasonable, but seems fine so I'm posting it.

In my application, I'm using actix_redis for session management.
One time, a user who has no key in the session (not called `session.set()` yet) visited the route which calls `session.purge()` function.

Since there is no key in his session, there is nothing to purge.
So I was expecting to respond 200, but got 500.

When I looked into the code, it looked like such 500-error was created here.
https://github.com/actix/actix-extras/blob/50621bae7168b689d79fe789ce6b26fd202790f6/actix-redis/src/session.rs#L184-L194

If there is no key in the session, it seems to be OK that nothing needs to be done.
But is this idea correct?

I tried to follow the commit log, but I couldn't figure out why it was returning an Internal Server Error.
https://github.com/actix/actix-redis/pull/23

Thanks.

## Expected Behavior

If there are no keys in the session, the purge function will respond to 200.

## Current Behavior

If there are no keys in the session, the purge function will respond to 500.

## Your Environment

* rustc 1.49.0 (e1884a8e3 2020-12-29)
* actix-session = "0.4.0"
* actix-redis = "0.9.1"

**Comment by LukeMathWalker** [comment]
This should be fixed in `actix-session` `0.6.0` - we can close this @robjtede.
