### ISSUE TITLE
RedisSession Basic example does not work

### ISSUE THREAD

**Issue by SorenHolstHansen** [actix/actix-extras#206]
I tried running the RedisSession [basic example](https://github.com/actix/actix-extras/blob/master/actix-redis/examples/basic.rs), but updating dependencies.

However nothing was ever printed. The cookie was set every time, but the program was unable to ever read it. I think there is a problem with `session.get()`

What am i doing wrong

```rust
use actix_redis::RedisSession;
use actix_session::Session;
use actix_web::{web, App, Error, HttpServer, Responder};

/// simple handler
async fn index(session: Session) -> Result<impl Responder, Error> {
    // session
    if let Some(count) = session.get::<i32>("counter")? {
        println!("SESSION value: {}", count);
        session.set("counter", count + 1)?;
    } else {
        session.set("counter", 1)?;
    }

    Ok("Welcome!")
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            // cookie session middleware
            .wrap(RedisSession::new("127.0.0.1:6379", &[0; 32]))
            // register simple route, handle all methods
            .service(web::resource("/").to(index))
    })
    .bind("0.0.0.0:8080")?
    .run()
    .await
}
```

```toml
[dependencies]
actix-web = "3.3.2"
actix-session = "0.4.1"
actix-redis = "0.9.2"
```

**Comment by SorenHolstHansen** [comment]
Nvm, problem with my redis

**Comment by tami5** [comment]
@SorenHolstHansen I'm having the same exact issue, can you hint what what the problem with redis. I have it installed through brew

**Comment by SorenHolstHansen** [comment]
I can't remember now, sorry for not providing a solution when I found it. I think i uninstalled and installed redis, but I am not sure

**Comment by tami5** [comment]
> I can't remember now, sorry for not providing a solution when I found it. I think i uninstalled and installed redis, but I am not sure. Or maybe the problem was that redis was not running. You have to start it with brew

No issues, It was something wrong how I configured the middleware. Now it work find, Thank you
