### ISSUE TITLE
HttpAuthentication middleware cannot be used on Scope

### ISSUE THREAD

**Issue by simon-an** [actix/actix-extras#214]
## Expected Behavior
HttpAuthentication  middleware can be on scope.

## Current Behavior
This works:
``` rust
let auth = HttpAuthentication::basic(validator);
App::new()
            .wrap(auth);
``` 
But this does not compile:
``` rust
let auth = HttpAuthentication::basic(validator);
App::new()
     .service(
                web::scope("/api")
                .wrap(auth));
``` 

```
the trait bound `actix_web::Scope<impl ServiceFactory<ServiceRequest>, EitherBody<BoxBody>>: HttpServiceFactory` is not satisfied
the following implementations were found:
  <actix_web::Scope<T> as HttpServiceFactory>
```

Not sure where the issue is, but comparing the signatures of app and scope they are slightly different.

``` rust
actix_web::scope::Scope
pub fn wrap<M, B1>(self, mw: M) -> Scope<impl ServiceFactory<ServiceRequest, Config = (), Response = ServiceResponse<B1>, Error = Error, InitError = ()>, B1>
where
    M: Transform<T::Service, ServiceRequest, Response = ServiceResponse<B1>, Error = Error, InitError = ()>,
```
``` rust
actix_web::app::App
pub fn wrap<M, B, B1>(self, mw: M) -> App<impl ServiceFactory<ServiceRequest, Config = (), Response = ServiceResponse<B1>, Error = Error, InitError = ()>>
where
    T: ServiceFactory<ServiceRequest, Response = ServiceResponse<B>, Error = Error, Config = (), InitError = ()>,
    B: MessageBody,
    M: Transform<T::Service, ServiceRequest, Response = ServiceResponse<B1>, Error = Error, InitError = ()>,
    B1: MessageBody,
```

* Rust Version 1.57
* Actix Web Version: 4.0.0-beta.14
* actix-web-httpauth = "=0.6.0-beta.5 (master branch)

**Comment by aliemjay** [comment]
`HttpAuthentication` middleware now needs to be wrapped in `actix_web::middleware::Compat` when used in `Scope` and `Resource`. This is true for any middlware that has a response body type other than `BoxBody`.

You can check the response body type of any midleware in the `impl Transform -> type Response=ServiceResponse<BodyTypeHere>` section in its doc page.

**Comment by simon-an** [comment]
Thanks, i hope this will find its way to the docs. 
I am still a bit confused, because this Middleware does not need Compat:

```rust
impl<S, B> Transform<S, ServiceRequest> for RequestTracing
where
    S: Service<ServiceRequest, Response = ServiceResponse<B>, Error = Error>,
    S::Future: 'static,
    B: 'static,
{
    type Response = ServiceResponse<B>;
    type Error = Error;
    type Transform = RequestTracingMiddleware<S>;
    type InitError = ();
    type Future = Ready<Result<Self::Transform, Self::InitError>>;

    fn new_transform(&self, service: S) -> Self::Future {
        ok(RequestTracingMiddleware::new(
            global::tracer_with_version("actix-web-opentelemetry", env!("CARGO_PKG_VERSION")),
            service,
            self.route_formatter.clone(),
        ))
    }
}
```

Meanwhile, i added a pull request which adds two tests.

**Comment by aliemjay** [comment]
> I am still a bit confused, because this Middleware does not need Compat:

This should mean that output body type of this middleware (`B`) is the same as the body type of the service it wraps (which may be another middleware). So, it doesn't need `Compat` if the downstream services output `BoxBody`
