### ISSUE TITLE
actix-protobuf does not support actix-web 4 RC 2

### ISSUE THREAD

**Issue by ichibanbrew** [actix/actix-extras#221]
## Current Behavior

Issue occurs when using _actix-protobuf_ with _actix-web_ version **4.0.0-rc.2**.

    HttpResponse::Ok().protobuf(data);

With the above code I get the error.

    `no method named `protobuf` found for struct `HttpResponseBuilder` in the current scope`

## Possible Solution

The current solution is to downgrade _actix-web_ to "3.3.3".

## Steps to Reproduce (for bugs)

Use the following crate versions in Cargo.toml:

    [dependencies]
    actix-protobuf = "0.6.0"
    actix-web = "4.0.0-rc.2"

Then try to use: `HttpResponse::Ok().protobuf(...);` in actix web app.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.58.0 (02072b482 2022-01-11)
* Actix-* crate(s) Version:
actix-protobuf = "0.6.0"
actix-web = "4.0.0-rc.2"

**Comment by robjtede** [comment]
you need to also use the actix-protobuf prerelease (latest: `0.7.0-beta.4`)
