### ISSUE TITLE
actix-protobuf does not support prost 0.9.0

### ISSUE THREAD

**Issue by ichibanbrew** [actix/actix-extras#222]
Your issue may already be reported!
Please search on the [actix-extras issue tracker](https://github.com/actix/actix-extras/issues) before creating one.

## Current Behavior

Using this example [actix-extras: prost-example](https://github.com/actix/actix-extras/blob/master/actix-protobuf/examples/prost-example/src/main.rs), but with latest packages I run into issues. 

The following is the `Cargo.toml`.

    [dependencies]
    actix-protobuf = "0.7.0-beta.4"
    actix-web = "4.0.0-rc.2"
    bytes = "1.1.0"
    prost = {version = "0.9.0", default_features = false, features = ["prost-derive"] }
    
    [build-dependencies]
    prost-build = "0.9.0"

Using the following controller:
    
    async fn index(msg: ProtoBuf<MyObj>) -> Result<HttpResponse> {
        println!("model: {:?}", msg);
        HttpResponse::Ok().protobuf(msg.0) // <- send response
    }

I get an error on `ProtoBuf<MyObj>`:

    the trait bound `MyObj: prost::message::Message` is not satisfied

## Possible Solution

The solution is to downgrade to older version of `prost`.

    prost = {version = "0.8.0", default_features = false, features = ["prost-derive"] }

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.58.0 (02072b482 2022-01-11)
* Actix-* crate(s) Version:

**Comment by robjtede** [comment]
addressing in https://github.com/actix/actix-extras/releases/tag/protobuf-v0.7.0-beta.5
