### ISSUE TITLE
Fails to provide proper CORS headers

### ISSUE THREAD

**Issue by toadslop** [actix/actix-extras#227]
I have the following configuration:

```
 HttpServer::new(move || {
        let cors = Cors::default()
            .allowed_origin("http://localhost:3000")
            .allowed_methods(vec!["GET", "POST"]);

        App::new()
            .app_data(Data::new(state.clone()))
            .wrap(cors)
            .configure(general_routes)
            .configure(private_routes)
            .default_service(web::route().to(not_found))
    })
    .bind(env.app.host_port().clone())?
    .run()
    .await
```

## Expected Behavior
It should return the proper CORS headers.

## Current Behavior
It does not return the proper headers.
Except, in the following strange case:
1. I use ::permissive instead of ::default
2. I start the application.
3. I shut down the application.
4. I return to ::default
5. I start the application again
6. Suddenly cors works.

However, if I shut down my computer and start it again, I have to do this process all over again.

## Possible Solution
I have no idea what could be causing this.

## Steps to Reproduce (for bugs)
1. Create app with Actix 4.0.1
2. Use the CORS settings shown above.
3. Start app
4. Make a POST request from the latest Chrome version

## Context
I'm just trying to implement the most basic of CORS policies.

## Your Environment
Windows 10, but app is compiled in and launche from WSL.

* Rust Version: rustc 1.58.1 (db9d1b20b 2022-01-20)
* Actix-* crate(s) Version: 4.0.1

**Comment by pnowosie** [comment]
👍  Experiencing same here with `Cors::default().send_wildcard()` and don't get any cors-header in response.

Rust: 1.58.1, actix-web 4.0, Ubuntu 20.04

Tested with:
```bash
curl -v -XOPTIONS <IP> -H 'Origin: myhost.net' -H 'Access-Control-Request-Method: POST'
```

**Comment by robjtede** [comment]
Can you both also provide the `actix-cors` version please? `cargo tree -i actix-cors`

**Comment by pnowosie** [comment]
> Can you both also provide the `actix-cors` version please? `cargo tree -i actix-cors`

actix-cors v0.6.0

**Comment by robjtede** [comment]
There was a minor issue with the CORS example; it's fixed now.

@toadslop `Cors::default()` is intentionally restrictive. You need to configure your parameters to allow the Origin. Docs give a good explanation.

**Comment by robjtede** [comment]
@toadslop `default` has no max-age (TTL) but `permissive` does. This is the difference and why restarting clears the cache. This is working as intended.
