### ISSUE TITLE
actix-session 0.6.0: regression. Auto-prolonged sessions are not available anymore

### ISSUE THREAD

**Issue by andy128k** [actix/actix-extras#231]
## Expected Behavior

Previous versions of actix-session allowed to create auto-prolonged sessions by specifying `expires_in`.

## Current Behavior

Current implementation allows fixed-length session only (`SessionLength::Predetermined`).

## Context

Typical usage of session is to store some kind of user id, so session is not changed much. Auto-prolonged session is common scenario when users are kept logged in till they interact with a website.

**Comment by robjtede** [comment]
related #37 
cc: @LukeMathWalker
