### ISSUE TITLE
actix-session package not making proper cookies.

### ISSUE THREAD

**Issue by Haider-Ali-Dev** [actix/actix-extras#240]
## Current Behavior

Hey I'm using the actix-session cookies crate to make add sessions functionality into my app, after spending 2-3 weeks on this I realized there is nothing with my code, its a bug in the crate. It is not storing the cookies in the localstorage, it is sending them in the response without the age attribute and also sending the wrong data to the frontend.
For instance:
```rs
.wrap(
                SessionMiddleware::builder(
                    RedisActorSessionStore::new(redis_connection_string),
                    secret_key.clone(),
                )
                .cookie_same_site(SameSite::None)
                .cookie_secure(false)
                .cookie_http_only(false)
                .session_length(SessionLength::BrowserSession {
                    state_ttl: Some(Duration::new(259200, 259200)),
                })
                .build(),
            )
 ```       
I'm wrapping this middleware around my app, the age is set to 3 days, I don't see the correct data being sent, I'm sending `session_id` in the cookie I see 
```id=ckC7B3g6dtME+qHiMmPkvAX+Njre0pLlGl2LGhR9CGmfi4Zlp/xUcQYPOL+ubOx2XUcdCGi/gialivVVjqEg2fmXSq0BJRFgcbmfqQNZtMKT1NRi5eXUo9ErKqk=; Secure SameSite=None; Path=/```

```
 session.insert("session_id", &user.id.reveal().to_string()).unwrap();
```
I'm not able to implement sessions into my app because of this bug, I hope it gets fixed. 

Your issue may already be reported!
Please search on the [actix-extras issue tracker](https://github.com/actix/actix-extras/issues) before creating one.

* Rust Version (I.e, output of `rustc -V`): rustc 1.59.0 (9d1b2106e 2022-02-23)
* Actix-* crate(s) Version: actix-session = { version = "0.6.1", features = ["redis-actor-session"] }
* actix-web = {version = "4.0.1", features = ["cookies"]}

**Comment by eribol** [comment]
I do not know it is same issue but it seems it is. I am not using cookie wrapper and i only insert some data to session but every time i insert data to session, it also creates a cookie named with id and when it happenes, for every request log says
`The session cookie attached to the incoming request failed to pass cryptographic checks (signature verification/decryption).`

**Comment by eribol** [comment]
I found my problem. I was creating secret key in App closure and because of it, key was always changing and break the encriptions.

**Comment by Haider-Ali-Dev** [comment]
Issue is solved, I was looking at the client cookies and looks like cross origin cookies are saved on the backend cookie storage.
