### ISSUE TITLE
[actix_identity] Regression: lost access to identity cookie configuration

### ISSUE THREAD

**Issue by e-rhodes** [actix/actix-extras#261]
In the 0.5 rewrite, the `IdentityMiddleware` hides more of the details of the cookie configuration than in the previous version. For the most part, the defaults are well chosen and it "just works", but there's a few places where I'd like to have access to the underlying cookie.

In particular:
1. The cookie name (now set to `id`). This constitutes a breaking API change for my server, since users that are managing that cookie manually will no longer be able to preserve their sessions.
2. The `Domain` attribute. I need this to use the cookie across subdomains.

Access to the `SameSite`, `HttpOnly`, and `Path` fields would also be useful, but less necessary for my use case. Ideally, all the same `CookieBuilder` methods would be exposed as in 0.4.

**Comment by LukeMathWalker** [comment]
You can still configure all those things. 
Given that `actix-identity` is now built on top of `actix-session`, they share the same cookie and the configuration options for it live in `actix-session` itself - on [`SessionMiddlewareBuilder`](https://docs.rs/actix-session/latest/actix_session/config/struct.SessionMiddlewareBuilder.html) to be precise.

You can use:
- [change the cookie name](https://docs.rs/actix-session/latest/actix_session/config/struct.SessionMiddlewareBuilder.html#method.cookie_name);
- [change the `Domain` attribute](https://docs.rs/actix-session/latest/actix_session/config/struct.SessionMiddlewareBuilder.html#method.cookie_domain);
- etc.

I hope that helps!

**Comment by e-rhodes** [comment]
Oh awesome, I don't know how I missed that! Thank you!!
