### ISSUE TITLE
Other serialization for session

### ISSUE THREAD

**Issue by pickfire** [actix/actix-extras#28]
Is it possible to use a more minimal and simpler serialization for session? Does it have to be json for session?

**Comment by LukeMathWalker** [comment]
What problem are you trying to solve by changing the serialization format?

**Comment by LukeMathWalker** [comment]
Question-aside, this is actually supported now - you just need to define a custom `SessionStore` implementation.
You are passed a `HashMap<String, String>` containing the session data - you can choose to serialize and deserialize it using whatever format you like.

**Comment by pickfire** [comment]
I think this have changed since last time, I don't recall what was the original issue, I guess can just close it.
