### ISSUE TITLE
actix-session's cookie SameSite attribute is not being set

### ISSUE THREAD

**Issue by Sh-u** [actix/actix-extras#282]
## Expected Behavior

I want HttpResponse to remove the cookie from the client-side.
The **set-cookie** header should look something like this: 
`myCookie=; HttpOnly; Secure; SameSite=None; Path=/; Max-Age=0; Expires=Thu, 02 Sep 2021 13:40:05 GMT`

## Current Behavior

When calling `session.purge()` in logout handler, the cookie set in HttpResponse doesn't have a SameSite attribute set to None, so it defaults to Lax, even after I explicitly set it to None.
**set-cookie** header looks like this:
`myCookie=; HttpOnly; Path=/; Max-Age=0; Expires=Thu, 02 Sep 2021 13:40:05 GMT`

```
 App::new()
            .wrap(
                SessionMiddleware::builder(
                    RedisActorSessionStore::new("127.0.0.1:6379"),
                    private_key.clone(),
                )
                .cookie_path("/".to_owned())
                .cookie_name("myCookie".to_owned())
                .cookie_same_site(SameSite::None)
                .cookie_secure(true)
                .build(),
            )

```
I literally set it to **SameSite::None** in the middleware..

Here is my route handler: 

```
#[post("/logout")]
pub async fn logout(session: Session) -> Result<HttpResponse, CustomError> {
    if !is_signed_in(&session) {
        return Err(CustomError::new(400, "There is no one signed in"));
    }

    session.purge();

    Ok(HttpResponse::Ok().finish())
}

```
## Your Environment

actix-web = "4.0"
actix-cors = "0.6.2"
actix-session = {version = "0.7.1", features = ["redis-actor-session"]}
actix-redis = {version = "0.12.0"}

**Comment by Sh-u** [comment]
Okay, after looking at `actix-session` **middleware.rs** source code I think I may have found the issue.
In the `set_session_cookie` function middleware is setting the specified `SameSite` attribute however in the `delete_session_cookie` function it's not setting the  `SameSite` attribute. 

Is there any reason for that?

Can I somehow modify the middleware's cookie while handling requests, like I'm able to modify the session?

**Comment by robjtede** [comment]
> Is there any reason for that?

Nope, good find and should be an easy fix so PR welcome.
