### ISSUE TITLE
Documentation implies that all headers are allowed by default

### ISSUE THREAD

**Issue by mmalenic** [actix/actix-extras#288]
The documentation of the `Cors` `allowed_headers` function implies that the default is to allow all headers, however this doesn't seem to be the case.

## Expected Behavior
`Cors::default()` should allow all headers according to the documentation of `allowed_headers`:

https://github.com/actix/actix-extras/blob/1561bda82268931edb070501413a46337ed71290/actix-cors/src/builder.rs#L279-L289

## Current Behavior
`Cors::default()` allows no headers. This aligns with the documentation of `Cors::default()`, however not with `allowed_headers`:

https://github.com/actix/actix-extras/blob/1561bda82268931edb070501413a46337ed71290/actix-cors/src/builder.rs#L454-L458

## Possible Solution
Change the documentation of `allowed_headers`, or change the implementation and documentation of `Cors::default()`.

Could be reading it wrong! Although it seems like an issue with the `allowed_headers` documentation.
Happy to make this change.

**Comment by robjtede** [comment]
It's a docs oversight. The Cors::default builder should allow nothing.

**Comment by mmalenic** [comment]
It looks like some other functions in the `Cors` builder are similar. For example, the [`allowed_origin`](https://github.com/actix/actix-extras/blob/1561bda82268931edb070501413a46337ed71290/actix-cors/src/builder.rs#L454-L458) and [`allowed_methods`](https://github.com/actix/actix-extras/blob/1561bda82268931edb070501413a46337ed71290/actix-cors/src/builder.rs#L209-L217) functions also have a mismatch between the function docs and default docs.
