### ISSUE TITLE
The method behavior of allowed_methods in actix_cors feels abnormal.

### ISSUE THREAD

**Issue by liuliuOD** [actix/actix-extras#319]
## Expected Behavior
When I use allowed_methods, I want to list a set of http methods that can request to server. But now this behavior not work.

## Current Behavior
Current behavior is like following, in [cors of examples repository](https://github.com/actix/examples/blob/master/cors/backend/src/main.rs) when I remove `POST` in allowed_methods then request `curl -X POST http://localhost:8080/user/info` it will response result beyond expectation.

My sample code is like following:
```rust
Cors::default()
        .allowed_origin("http://localhost:8080")
        .allowed_methods(vec!["GET"])
```

**Comment by robjtede** [comment]
> it will response result beyond expectation

Sorry, I don't understand this part.

**Comment by liuliuOD** [comment]
I expected that by only setting "GET" in the allowed_methods, any requests that use the "POST" method would respond with an error code such as "405 Method Not Allowed" or another similar message.
<img width="173" alt="Screen Shot 2023-04-05 at 2 49 29 PM" src="https://user-images.githubusercontent.com/44393673/230002986-6dde5fbe-0886-447f-b63f-cc57393399cc.png">

**Comment by liuliuOD** [comment]
Or perhaps I misunderstood the above speculation, and the behavior is not as I thought, but adding HTTP headers to the response.

[Doc](https://fetch.spec.whatwg.org/#http-cors-protocol)
<img width="641" alt="Screen Shot 2023-04-05 at 2 55 25 PM" src="https://user-images.githubusercontent.com/44393673/230004111-8de46365-a1be-4b3d-88fb-1cd4c1051312.png">

**Comment by robjtede** [comment]
Yeah CORS is not designed to prevent processing like this.
