### ISSUE TITLE
actix-redis depends on old version of package(s)

### ISSUE THREAD

**Issue by cerven** [actix/actix-extras#32]
dependencies should be upgraded. I have problem with package "time". Current version is 0.2.9, but actix-redis depends on 0.1.42, which is not compatible:
I want set .cookie_max_age(Duration::days(1))

**Comment by cerven** [comment]
I see, it is because actix-web depends on this version

**Comment by JohnTitor** [comment]
master branch already has latest time dependency, but yeah we should release it.
