### ISSUE TITLE
CORS allowed origin string is case sensitive

### ISSUE THREAD

**Issue by NotGovernor** [actix/actix-extras#354]
## Expected Behavior
The .allowed_origin("https://MyWebSite.com") will match on submitted origins with all cases.

IE any of:
"mywebsite.com"
"mYwEBsITE.CoM"
"MYWEBSITE.COM"
etc

## Current Behavior
The origin submitted from the browser or other source must match the case of the string submitted to the allowed_origin method exactly.

## Possible Solution
No other framework I'm aware of handles CORS rules with case sensitivity. I suggest mod'ing this to match industry standards.

**Comment by robjtede** [comment]
While [the Fetch Standard](https://fetch.spec.whatwg.org/#http-cors-protocol), where CORS is defined, only talks about the client-side implementation, [RFC 6454](https://datatracker.ietf.org/doc/html/rfc6454#section-5) offers a standard for comparing origins, stating that that they should be **identical**.

That said, and in practice, NodeJS' `cors` package does indeed [seem to be case-sensitive](https://github.com/expressjs/cors/blob/master/lib/index.js#L27-L28).
