### ISSUE TITLE
`generate_session_key()` could be public

### ISSUE THREAD

**Issue by kakserpom** [actix/actix-extras#434]
I've implemented my own session store and I had to copy-paste generate_session_key() instead of just calling it.

**Comment by robjtede** [comment]
Please open a different issue for the `SessionState` discussion.

---

I think the choice to keep it private is that it might not be a good choice for _all_ session implementations and that it just happens to work well for the built-in storage impls.

Seeing the desire to re-use it in 3rd party impls is a good indicator that it should be publicl; I'd accept a PR.

**Comment by robjtede** [comment]
If someone picks this up and creates a PR I think we should change the implementation to use `rand::DistString` to remove some unwraps: https://docs.rs/rand/0.8/rand/distributions/trait.DistString.html

**Comment by sjoqvist** [comment]
I really appreciate this change, but why does the function have to be hidden specifically behind the `redis-session` feature? I'm using the function as I'm implementing my own session store, i.e. I'm not using Redis. `redis-session` introduces a total of 12 new dependencies in my `Cargo.lock`.

**Comment by robjtede** [comment]
@sjoqvist removed the feature guard in v0.10.1
