### ISSUE TITLE
actix-redis  connect to the redis address with password

### ISSUE THREAD

**Issue by huiali** [actix/actix-extras#46]
when connecting to redis, how to set the access password of the address? When I connect to the redis address with password, no matter how I set it, the connection fails.

**Comment by huiali** [comment]
https://github.com/actix/examples/issues/338

**Comment by omid** [comment]
As far as I read about it, this ticket, https://github.com/actix/actix-extras/issues/30 will solve the issue.

**Comment by LukeMathWalker** [comment]
#212 will solve this issue.
