### ISSUE TITLE
Is it possible to user auth before uploading data to the server?

### ISSUE THREAD

**Issue by F1ndus** [actix/actix-extras#47]
I implemented a small Service that uploads media with http-multipart. I also added bearer auth as middleware.

i noticed that the server only authenticates the user when all data has been uploaded, so if I upload a file, that is several 100MB in size I would wait a couple of minutes before getting rejected.

Is there a way to check if the user provided the correct token before uploading any form data?

**Comment by vmalloc** [comment]
Do you have an example code to demonstrate the issue? It really depends on how exactly you extract the multipart upload from the request. Some methods are "eager" while others are lazy

**Comment by F1ndus** [comment]
@vmalloc yeah, I put it on github:
https://github.com/F1ndus/media-upload/

**Comment by vmalloc** [comment]
Just out of curiousity, did you check that the handler *does not read* from the stream? From a quick glance at the multipart extractor it doesn't seem like it actually consumes the stream on its own, so the wait you're  describing might simply be because the HTTP response isn't read in time.

**Comment by F1ndus** [comment]
@vmalloc sorry, now I found out what was the problem, it was not actix related at all, I set up reverse proxy in front of it and that seems to cache the request before passing it forward, if I debug it locally the request gets rejected instantly.

**Comment by vmalloc** [comment]
No problem! Glad you figured it out
