### ISSUE TITLE
Could not compile actix-redis 0.9.0-alpha.1

### ISSUE THREAD

**Issue by errmac-v** [actix/actix-extras#54]
When I try to build empty project with `cargo new`, I get an error `wrong number of type arguments: expected 3, found 2`. Is there an example with stable versions (it doesn't work for actix-redis 0.8 as well)? Or it can be fixed for alpha?

### src/redis.rs:30:18
```
cell: Option<actix::io::FramedWrite<WriteHalf<TcpStream>, RespCodec>>,
```
### Cargo.toml
```
[package]
name = "actix-redis-test"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
actix-redis = "0.9.0-alpha.1"
actix-web = "3.0.0-alpha.2"
```

**Comment by robjtede** [comment]
Fixed in ecc774450fcf965360578ca330a8cc0be508b934. Will be in next alpha.

**Comment by robjtede** [comment]
Pinning redis-async version is a temporary workaround also:

```toml
redis-async = "=0.6.1"
```

**Comment by robjtede** [comment]
@JohnTitor thoughts on patch release 0.8 for compat with redis-async `0.6.3`? (Seems like they broke semver upgrading tokio-util in a patch release.)

**Comment by JohnTitor** [comment]
> thoughts on patch release 0.8 for compat with redis-async `0.6.3`? 

I think we couldn't since actix 0.9 depends on tokio-util 0.2. I'll make an alpha release.

**Comment by robjtede** [comment]
We could also do a 0.8.2 with a pinned redis-async.

**Comment by errmac-v** [comment]
> Pinning redis-async version is a temporary workaround also:
> 
> ```toml
> redis-async = "=0.6.1"
> ```

This solution helps me on 0.8.1, thanks!

**Comment by JohnTitor** [comment]
> We could also do a 0.8.2 with a pinned redis-async.

Ah indeed we could! I'll submit a PR for it.
