### ISSUE TITLE
Firefox issue with session and static files

### ISSUE THREAD

**Issue by 0xmad** [actix/actix-extras#57]
I found some strange issue with Firefox (76.0.1) in my project.
### Cargo.toml
```
[package]
name = "actix-session-test"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
actix-files = "0.2.1"
actix-web = "2.0.0"
actix-rt = "1.1.1"
actix-service = "1.0.5"
actix-session = "0.3.0"
```
I created a minimal example for this issue with steps to reproduce https://github.com/errmac-v/actix-issue.
In general, when I try to open a static file (I use actix-files) and then reload this page, session is purging. It happens if I use `req.get_session()` in middleware.
Is it related to `actix-web` or `actix-extras` or it's a Firefox issue? It works well on Chrome, btw.

**Comment by realaravinth** [comment]
Are you still facing this issue? I am unable to reproduce the issue with the program that you have provided(tested on Firefox `91.0b7`, `90.0.2` and `76.0.1`). 

I love Firefox and I use it as my daily driver but it's privacy protection features break all sorts of things. My guess is either a Firefox feature or an extension broke cookies. It might also help to check Firefox's "enhanced tracking protection" configuration.

**Comment by robjtede** [comment]
closing as stale, there's been many releases since then that may hav fixed the issue
