### ISSUE TITLE
actix-protobuf does not support 3.0.0-alpha.3

### ISSUE THREAD

**Issue by NoGeneral** [actix/actix-extras#71]
## Steps to Reproduce (for bugs)

1.  when call `protobuf()` method
```
HttpResponse::Ok().protobuf(msg)
```
2.  compile error
```
no method named `protobuf` found for struct `actix_http::response::ResponseBuilder` in the current scope
method not found in `actix_http::response::ResponseBuilder`
```

## Your Environment

* Rust Version (I.e, output of `rustc -V`):  rustc 1.43.0-nightly (5d04ce67f 2020-02-13)
* Actix-* crate(s) Version: 
actix-web = "3.0.0-alpha.3"
actix-protobuf = "0.5"

**Comment by robjtede** [comment]
Please fill in the issue template. Do you mean does not support actix-web v3 alphas?
