### ISSUE TITLE
Strange `actix_identity::Identity` behavour when used with `configure`.

### ISSUE THREAD

**Issue by wowofbob** [actix/actix-extras#78]
Hi. I slightly changed [this example](https://github.com/actix/examples/blob/master/cookie-auth/src/main.rs) and got unexpected behavior. I added `configure` part after `wrap` with same three urls under scope `cfg`. Here is how it looks:

```rust
// main.rs
use actix_web::{web, App, HttpResponse, HttpServer};
use actix_identity::{Identity, CookieIdentityPolicy, IdentityService};

use rand::Rng;


async fn index(id: Identity) -> String {
    format!(
        "Hello {}",
        id.identity().unwrap_or_else(|| "Anonymous".to_owned())
    )
}

async fn login(id: Identity) -> HttpResponse {
    id.remember("user1".to_owned());
    HttpResponse::Found().header("location", "/").finish()
}

async fn logout(id: Identity) -> HttpResponse {
    id.forget();
    HttpResponse::Found().header("location", "/").finish()
}


#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .wrap(IdentityService::new(
                CookieIdentityPolicy::new(&rand::thread_rng().gen::<[u8; 32]>())
                    .name("test")
                    .max_age(60000)
                    .secure(false)
            ))
            // I added this part
            .configure(|cfg| {
                cfg.service(
                    web::scope("/cfg")
                        .service(web::resource("/login").route(web::post().to(login)))
                        .service(web::resource("/logout").to(logout))
                        .service(web::resource("/index").route(web::get().to(index)))
                );
            })
            .service(web::resource("/login").route(web::post().to(login)))
            .service(web::resource("/logout").to(logout))
            .service(web::resource("/").route(web::get().to(index)))
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}
```
```
[dependencies]
actix-rt = "1.0.0"
actix-web = { version="2.0.0" }
actix-identity = "0.2.0"
rand = "0.7.3"
```

## What happens
* I expect to see `Hello user1` on `/cfg/index` after posting to `/login`. I get `Hello Anonymous` instead.
* If you see `Hello user1`, then send **GET** to `/` after that. You might get `Hello Anonymous` there.
* In general. play with logging in at `/login` and sending **GET** to `/cfg/index`. Or go to `/` instead. Mix these four routes. You should get `Hello Anonymous` at some point. I don't see the whole pattern yet.

Is it a bug? If not, then please explain why does it work like this. I'm new to both *rust* and *actix*. I've checked out `actix_identity` sources and didn't find anything suspicious (I was looking for strange `forget`-like statements). My guess is that the service's value gets moved somewhere between `App` and `configure` parts and it's state being dropped. But it is too vague.

## Context
I moved part of routes to external module. I added identity service so I could extract user information from request. And than I got this behavior. It's wrong because clients I use (browser and postman) are being randomly kicked out.

## Your Environment
* Win10
* rustc 1.44.0 (49cae5576 2020-06-01)

**Comment by wowofbob** [comment]
Replaced `actix_identity` by `actix_session`. Now I'm able to login on `/login` and see `user1` at `/cfg/index` and vice versa. Either something is wrong with `actix_identity` (because when I see `Anonymous` cookie doesn't go anywhere, it's still there), or I don't understand how it works

**Comment by rlcurrall** [comment]
I believe it has something to do with how you are generating the `key` for the CookieIdentityPolicy.

First thing I did was change the code to match what is in the [actix-identity documentation](https://docs.rs/actix-identity/0.3.1/actix_identity/) which resolved the issue:

```rust
CookieIdentityPolicy::new(&[0; 32])
    .name("test")
    .max_age(60000)
    .secure(false)
```

Second thing I did was try using a hard coded random key, which also resolved the issue:

```rust
CookieIdentityPolicy::new(
    "SomE LoNg RanDOm K3y That Ha5 Lett3Rs AnD NUm83Rs".as_bytes()
)
.name("test")
.max_age(60000)
.secure(false)
```

**NOTE:** The second approach is how I've typically done this in the past, I'll have an environment variable set that I will load into the app and use:
```rust
CookieIdentityPolicy::new(
    std::env::var("APP_KEY")
        .expect("APP_KEY not set.")
        .as_bytes()
)
.name("test")
.max_age(60000)
.secure(false)
```
If you want this to be generated randomly at runtime rather than being set as an environment variable, then you can check out this [section of the Rust Cook Book](https://rust-lang-nursery.github.io/rust-cookbook/algorithms/randomness.html#create-random-passwords-from-a-set-of-alphanumeric-characters) on crating random keys from alphanumeric characters.

**Comment by rlcurrall** [comment]
Did a bit more playing around and found that if you were to declare your key outside of the closure passed to `HttpServer::new(/* ... */)` it works as expected. Maybe some issue with the lifetime of the key reference? Here is the code that I used to allow this to work:

```rust
    // ...

    let key = rand::thread_rng().gen::<[u8; 32]>();

    HttpServer::new(move || {
        App::new()
            .wrap(IdentityService::new(
                CookieIdentityPolicy::new(&key)
                    .name("test")
                    .max_age(60000)
                    .secure(false),
            ))
            // register handlers ...
    })
    // ...
```
