### ISSUE TITLE
CORS Issue when requesting backend apis

### ISSUE THREAD

**Issue by helabenkhalfallah** [actix/actix-extras#79]
Hello, I have an issue with CORS.
I had added CORS config in my server : 
https://github.com/helabenkhalfallah/rust-rest-api/blob/master/src/main.rs#L59

## Expected Behavior
Frontend request can get data from my backend.

## Current Behavior
I have this issue when calling requests from frontend : 

`Access to fetch at 'http://localhost:4000/get-all-users' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

https://github.com/helabenkhalfallah/rust-react-wasm-js/blob/master/src/lib.rs#L116

## Steps to Reproduce (for bugs)
1. launch backend
2. launch frontend
3. each frontend request fails.

## Context
Consuming backend APIs from my frontend.

## Your Environment
* Rust Version (I.e, output of `rustc -V`): rustc 1.44.1
* Actix Web Version: 2

Have I missed a config ?

Thank you so much for your help :) :)

**Comment by robjtede** [comment]
You shouldn't put * as the origin, just leave it blank. This is common pitfall.

**Comment by helabenkhalfallah** [comment]
Hello @robjtede , thank you for your response.
I tried now but I get : 

```
[2020-07-12T17:32:35Z INFO  actix_server::builder] Starting 16 workers
thread 'actix-rt:worker:2' panicked at 'empty string', /Users/helabenkhalfallah/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-cors-0.2.0/src/lib.rs:487:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2020-07-12T17:32:35Z INFO  actix_server::builder] Starting "actix-web-service-0.0.0.0:4000" service on 0.0.0.0:4000
thread 'actix-rt:worker:0' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /Users/helabenkhalfallah/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/server.rs:250:25
```

**Comment by robjtede** [comment]
Did you remove the call to allowed_origin entirely?

**Comment by helabenkhalfallah** [comment]
No, I leave it blank : 

```
 // cors
        let cors_middleware = Cors::new()
            .allowed_origin("")
            .allowed_methods(vec!["GET", "POST", "DELETE", "PUT"])
            .allowed_headers(vec![http::header::AUTHORIZATION, http::header::ACCEPT])
            .allowed_header(http::header::CONTENT_TYPE)
            .max_age(3600)
            .finish();
```

**Comment by helabenkhalfallah** [comment]
Aha removing the line works now ! Thank you so much ! 💯

**Comment by helabenkhalfallah** [comment]
```
        let cors_middleware = Cors::new()
            .allowed_methods(vec!["GET", "POST", "DELETE", "PUT"])
            .allowed_headers(vec![http::header::AUTHORIZATION, http::header::ACCEPT])
            .allowed_header(http::header::CONTENT_TYPE)
            .max_age(3600)
            .finish();
```
