### ISSUE TITLE
HttpAuthentication middleware doesn't behave properly on tests

### ISSUE THREAD

**Issue by ManevilleF** [actix/actix-extras#90]
## Expected Behavior
When using a custom `HttpAuthentication` middleware with a `process_fn` looking like this: 
``` Rust
pub async fn bearer_token_middleware(mut req: ServiceRequest, credentials: BearerAuth) -> Result<ServiceRequest, Error> {
    let session = match
        Session::find_by("token", credentials.token(), &req.app_data().unwrap()).await
        {
            Ok(record) => record,
            Err(_error) => return Err(MyErrors::Unauthorized))
        };
    req.headers_mut().insert(http::HeaderName::from_static(USER_ID), session.record.user_id.parse()?);
    Ok(req)
}
```
that simply checks the bearer token and stores a new header value containing the associated user id, it should work. And it does at runtime, however when testing (`actix tests`) it should behave the same

the following extract from a test I wrote:
``` Rust
let mut app = tokio_test::block_on(test::init_service(
                App::new()
                    .data(dbPool.clone())
                    .configure(config::web_service::config_routes)
            ));
let token = String::from("Wrong bearer');
let req = test::TestRequest::get()
                .uri(&format!("/api/users/{}", &user_id))
                .header(http::header::AUTHORIZATION, token)
                .to_request();
let resp = tokio_test::block_on(test::call_service(&mut app, req));
assert!(!resp.status().is_success());
```
this test should succeed but instead it fails because `test::call_service` panics on error (unwrap). The middleware doesn't seem to build a response when working with tests, and instead returns a `Result<ServiceResponse, Error>`

CLI result: ```$TEST panicked at 'called `Result::unwrap()` on an `Err` value: Unauthorized'``` the panic is not from my code but from the `actix-web::test::call_service` function at `github.com-1ecc6299db9ec823/actix-web-2.0.0/src/test.rs:123:5`

I am on the last versions of all actix crates.

thanks for your help

**Comment by robjtede** [comment]
fixed in 0.7.0
